apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.backend.name | default "shop-backend" }}
spec:
  host: {{ .Values.exposition.hostname }}
  path: /api
  port:
    targetPort: {{ .Values.backend.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.backend.name | default "shop-backend" }}
